-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versione server:              5.5.36 - MySQL Community Server (GPL)
-- S.O. server:                  Win32
-- HeidiSQL Versione:            8.3.0.4792
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dump della struttura di tabella quiz.interview
CREATE TABLE IF NOT EXISTS `interview` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `question` varchar(150) DEFAULT NULL,
  `topics` varchar(150) DEFAULT NULL,
  `answer` text,
  `position` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `position` (`position`)
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=latin1;

-- Dump dei dati della tabella quiz.interview: ~37 rows (circa)
/*!40000 ALTER TABLE `interview` DISABLE KEYS */;
INSERT INTO `interview` (`id`, `question`, `topics`, `answer`, `position`) VALUES
	(1, 'What is PHP?', 'Language', 'PHP is an open source server side scripting language used to develop dynamic websites. PHP  stands for Hypertext Preprocessor, also stood for  Personal Home Page. Now the implementations of PHP is produced by The PHP group. It was created by Rasmus lerdorf in 1995. It is a free software released under the PHP license.', 1),
	(2, 'Who is the father of PHP?', 'Language', 'Rasmus Lerdorf known as the father of PHP. Php was created by Rasmus Lerdorf In 1995', 2),
	(3, 'Which is the latest version of PHP?', 'PHP Version', 'The latest stable version of PHP is 5.5.14 released at 27 June 2014', 3),
	(4, 'What is the difference between session and cookies?', 'Session and Cookies', 'There are some difference between session and cookies thath are as following:\r\n\r\n			<ol>\r\n				<li>Session are temporary and Cookies are parmanent</li>\r\n				<li>Session data is store on server while Cookies are store on user\'s computer</li>\r\n				<li>Cookies contents can be easily modify but to modify Session contents is very hard</li>\r\n				<li>Cookies could be save for future reference but Session couldn\'t when user close the browser Session data also lost</li>\r\n			</ol>', 6),
	(5, 'What is the current version of Apache?', 'Syntax', 'The latest stable version of  Apache is 2.4.9, released  on 17th  March 2014.', 5),
	(6, 'What is difference between unset and unlink?', 'Syntax', 'Unset is used to delete(destroy) a variable whereas unlink used to delete a file.', 4),
	(7, 'How we declare cookies and how we expire it?', 'Session and Cookies', '<p><strong>setcookie()</strong> function is used to set cookies in php.</p>\r\n<p>To declare Cookies syntax will be:</p>\r\n<i>setcookie(name, value, expire, path, domain);</i>\r\n<p>name    : Name of the cookie</p>\r\n<p>value     : Value of the cookie</p>\r\n<p>expire   : The time for cookie to expire</p>\r\n<p>path      : path to save the cookie where we want to save the cookie information</p>\r\n<p>domain  : domain name on which we want to save the cookie</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p><strong>e.g:</strong> <i>setcookie("username","harry",time()+60*60*60*24);</i></p>\r\n<p>In the above example the cookie name is username having value harry and set for one day.</p>\r\n<p>To expire cookies we have set the time of cookie in past</p>\r\n<p>To expire Cookies syntax will be: setcookie(name,value,time-3600);</p>', 7),
	(8, 'What is the difference between array_merge and array_combine?', 'Array', '<p><strong>array_merge</strong> merges the elements of one or more than one array such that the value of one array appended at the end of first array. If the arrays have same strings  key  then the later value overrides the previous value for that key.</p>\r\n<pre>\r\n<?php\r\n$array1 = array("course1" => "java","course2" => "sql");\r\n$array2 = array(("course1" => "php","course3" => "html");\r\n$result = array_merge($array1, $array2);\r\nprint_r($result);\r\n?>\r\nOUTPUT :  \r\narray\r\n(\r\n[course1] => php\r\n[course2] => sql\r\n[course3] => html\r\n)\r\n</pre>\r\n\r\n<p>Array_combine creates a new array by using the key of one array as keys and using the value of other array as values.</p>\r\n\r\n<pre>\r\n<?php\r\n$array1    = array("course1","course2");\r\n$array2    = array(("php","html");\r\n$new_array = array_combine($array1, $array2);\r\nprint_r($new_array);\r\n?>\r\nOUTPUT :\r\narray\r\n(\r\n[course1]  => php\r\n[course2]    => html\r\n)\r\n</pre>', 8),
	(9, 'What is use of var_dump?', 'Syntax', 'var_dump() function is used to display structured information(type and value) about one or more variable.\r\nsyntax:- var_dump(variable1,variable2,.....variablen);\r\ne.g   \r\n<pre><?php\r\n          $a=3.1;\r\n          $b=true;\r\n          var_dump($a,$b);\r\n         ?>\r\noutput   :  float(3.1)\r\n              bool(true)\r\n</pre>', 9),
	(10, 'What is str_replace()?', 'Strings', '<p>This function replace some characters with some other characters in a string , this function is case sensitive.</p>\r\n<p>syntax:- str_replace(find,replace,string);</p>\r\n<p>&nbsp;</p>\r\n<p>find:-required,specifies the value to find.</p>\r\n<p>replace:-required,specifies the value to replace the value in find.</p>\r\n<p>string:-required,specifies the string to searched.</p>\r\n<p>&nbsp;</p>\r\n<p>for examlpe:</p>\r\n<pre>\r\n<?php\r\necho str_replace("world","india","hello world");\r\n?>\r\n</pre>\r\n<p>output: -  hello india</p>', 10),
	(11, 'What are the differences between require and include, include_once and require_once?', 'Syntax', '<p>The <strong>include()</strong> statement includes and evaluates the specified <span class="skimlinks-unlinked">file.The</span> documentation below also applies to <strong>require()</strong>. The two constructs are identical in every way except how they handle<br>\r\nfailure. <strong>include()</strong> produces a Warning while <strong>require()</strong> results in a Fatal Error. In other words, use<br>\r\n<strong>require()</strong> if you want a missing file to halt processing of the page.  <strong>include()</strong> does not behave this way, the script will continue regardless. The <strong>include_once() </strong>statement includes and evaluates the<br>\r\nspecified file during the execution of the script. This is a behavior similar to the <strong>include() </strong>statement, with the only difference being that if the code from a file has already been included, it will not be<br>\r\nincluded again. As the name suggests, it will be included just once.<strong>include_once() </strong>should be used in cases where the same file might be included and evaluated more than once during a particular execution of a script, and you want to be sure that it is included exactly once to avoid problems with function redefinitions, variable value reassignments, etc. <strong>require_once() </strong>should be used in cases where the same file might be included and evaluated more than once during a particular execution of a script, and you want to be sure that it is included exactly once to avoid problems with function<br>\r\nredefinitions, variable value reassignments, etc.</p>', 11),
	(12, 'What is final class?', 'OOP', '<p>final class is a class that can not be inherited.Its protect the methods of class to be overriden by the child classes.</p>\r\n<strong>e.g.</strong>\r\n<pre>final class baseclass\r\n            {\r\n                public function mymethod()  {\r\n                          echo  "baseclass method";\r\n                            }\r\n\r\n            }\r\n\r\n            class derivedclass extends baseclass\r\n             {\r\n                        public function mymethod() {\r\n                                 echo   "derivedclass method";\r\n\r\n                              }\r\n\r\n               }\r\n\r\n          $c= new derivedclass();\r\n          $c->mymethod();\r\n</pre>\r\n<p>In the above example base class is declared as final and hence can not be inherited. Derived class tries to extends baseclass then compile error will be generated</p>', 12),
	(13, 'What is difference between abstract class and interface classes?', 'OOP', '<strong>Interface:</strong> An interface does not contain any code,it contain only declaration of    methods,properties,events. Interfaces allow us to code which specifies which methods a class must have implement . Interfaces defines with the word interface . All methods in interfaces must be public\r\n           <strong>e.g :</strong><pre>interface myItem\r\n                    {\r\n\r\n                        void Id();\r\n                       string description();\r\n                        string Runtest(int testnumber);\r\n\r\n                    }\r\n</pre>\r\n\r\n<p><strong>Abstract class :</strong> Abstract classes are look like interfaces. Abstract classes may contain code although it may also have abstract method that do not have code. Abstract classes defines only signature of the method ,not implementation.  \r\nThe child class which inherit the abstarct class must define all the abstarct methods of its parent class .</p>\r\n\r\n         <strong>e.g :</strong><pre>abstract class myItem\r\n                    {\r\n\r\n                        abstract protected function getitem();\r\n                        abstract protected function setitem();\r\n\r\n                    }</pre>', 13),
	(14, 'What is difference between echo() and print()?', 'Syntax', '<p><strong>echo()</strong> and <strong>print()</strong> function both are used to show the output on the visitors screen but in echo we can take  one or more parameters.</p>\r\n\r\n<p><strong>print()</strong> has a return value of true or false whereas echo has a void return type.</p>\r\n\r\n <p><strong>echo()</strong> is slightly faster than print.</p>', 14),
	(15, 'What is the difference between PHP4 and PHP5?', 'PHP Version', 'There are some difference between PHP4 and PHP5 that are as following:\r\n<ol>\r\n      <li>In PHP5 abstract classes are used but not used in PHP4</li>\r\n      <li>In PHP5 interfaces are used but not used in PHP4</li>\r\n      <li>In PHP5 visibility are used but not used in PHP4</li>\r\n      <li>In PHP5 magic methods are used but not uesd in PHP4</li>\r\n      <li>In PHP5 typehinting are used but not used in PHP4</li>\r\n      <li>In PHP5 cloning are used but not used in PHP4</li>\r\n      <li>In PHP5 construtor are written as __construct keyword but in PHP4 are written as class name </li>\r\n</ol>', 15),
	(16, 'Why do we use ob_start()?', 'Cache', '<strong>Ob_start used</strong> to active the output buffering.When output buffering is on all output of the page sent at one time to the browser ,otherwise sometimes we face headers already sent type errors.', 16),
	(17, 'What is a .htacces file?', 'Htaccess', '<p>.htaccess is a configuration file running on Apache server.These .htaccess file used to change the functionality and features of apache web  server.</p>\r\n\r\n<p><strong> e.g</strong>   .htaccess file used for url rewrite .</p>\r\n<p>.htaccess file used to make the site password protected.</p>\r\n<p>.htaccess file can restrict  some ip addresses, so that on restricted ip adresses  site will not open.</p>', 17),
	(18, 'Is PHP an interpreted language or compiler language?', 'Language', 'PHP is an interpreted language.', 18),
	(19, 'What is the difference between compiler language and interpreted language?', 'Language', '<p><strong>Interpreted language</strong> executes line by line  , if there is some error on a line it stops the execution of script.</p>\r\n\r\n<p><strong>Compiler language</strong> can execute the whole script at a time and gives all the errors at a time. It does not stops the execution of script ,if there is some error on some line.</p>', 19),
	(20, 'What are web services in PHP?', 'Web services', 'Web services converts our applicaton into a web-application, which can publish its functions and messages to the internet users. The main web services platform is XML and HTTP. Web services can be published, found and used through web', 20),
	(21, 'What is static methods and properties in PHP?', 'OOP', 'A <strong>static</strong> method is accessible without needing instantiation of  a class. It means there is no need to make an  object to call the static methods .Static  methods and properties can be directly call from its class name with (::)  a scope resolution operator. They cannot be call from the object of its class. We need static methods to overcome   long overhead of instantiation of classes .\r\n<strong>e.g:</strong>\r\n<pre>\r\n<?php\r\nClass foo\r\n{\r\n      public static  $variable_name = \'it is a static variable\';\r\n} \r\n\r\necho foo :: $variable_name;      // Output:  it is a static varaible\r\n\r\n?>\r\n</pre>', 21),
	(22, 'What are magic methods in PHP?', 'OOP', '<p><strong>Magic methods</strong> are very easy to identify, that every magical method name is started with double underscore( __)sign. We can not declare any user-defined functions with __ sign.<br>\r\n<br>\r\nSome magic methods are <strong>:</strong></p>\r\n<p><br>\r\n__construct() , __destruct()&nbsp; ,&nbsp;&nbsp;&nbsp; __call()&nbsp;&nbsp; ,&nbsp; __callStatic()&nbsp; ,&nbsp; __get(),&nbsp; __set()&nbsp;&nbsp;&nbsp;&nbsp; , __isset()&nbsp;&nbsp;&nbsp;&nbsp; ,__unset()</p>\r\n<p>,&nbsp; __sleep()&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ,&nbsp; __wakeup(),&nbsp;&nbsp; __toString()&nbsp; , __invoke()&nbsp;&nbsp;&nbsp; , __set_state() ,&nbsp; __clone().</p>', 22),
	(23, 'What is the difference between GET and POST methods?', 'HTTP', '<p><strong>GET Method:</strong></p>\r\n<ol>\r\n<li>All the name value pairs are submitted as a query string in URL</li>\r\n<li>It\'s not secured</li>\r\n<li>Length of the string is restricted about 256</li>\r\n<li>If method is not mentioned in the Form tag, this is the default method used.</li>\r\n<li>Data is always submitted in the form of text.</li>\r\n<li>It has some limit like only 2Kb data able to send for request</li>\r\n</ol>\r\n \r\n<p><strong>POST Method:</strong></p>\r\n<ol>\r\n<li>All the name value pairs are submitted in the Message Body of the request.</li>\r\n<li>Length of the string (amount of data submitted) is not restricted.</li>\r\n<li>Post Method is secured because Name-Value pairs cannot be seen in location bar of the web browser.</li>\r\n<li> If post method is used and if the page is refreshed it would prompt before the request is resubmitted.</li>\r\n<li>If the service associated with the processing of a form has side effects (for example, modification of a database or subscription to a service), the method should be POST.</li>\r\n<lI>Unlimited data can we send</li>\r\n</ol>', 23),
	(24, 'What are access control modifiers in php?', 'OOP', 'Keywords <strong>public, protected and private</strong> are the three types of access control modifiers in php. With the help of these keywords we can manage the accessing  of a method or property of a class  in php.', 24),
	(25, 'What is difference between public, private and protected in php?', 'OOP', '<p><strong>Public:</strong></p>\r\n<p>The items which are declared public can be access from everywhere ie access from inside the class ,access in inherited class and   access from outside the class.</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Protected:</strong></p>\r\n<p>The items which are declared protected can be access inside the class that defines the item  and can acess in its child classes  (ie access in its inherited class) .</p>\r\n<p>&nbsp;</p>\r\n<p><strong>Private:</strong></p>\r\n<p>The items which are declared private can only be access inside its class that defines the item.</p>', 24),
	(26, 'How can we get all the properties of browser in PHP?', 'HTTP', 'We can get the browser properties in PHP by:\r\n<pre>\r\n<?php\r\n$_SERVER [\'HTTP_USER_AGENT\'];\r\n?>\r\n</pre>', 23),
	(27, 'How to get difference between two dates?', 'DateTime', '<pre>\r\n$firstdate           = "2010-10-07";\r\n$seconddate      = "2014-03-10";\r\n\r\n$differnce          = abs(strtotime($date2) - strtotime($date1));\r\n\r\n$years              =   floor($differnce / (365*60*60*24));\r\n$months           =   floor(($differnce - $years * 365*60*60*24) / (30*60*60*24));\r\n$days               =   floor(($differnce- $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));\r\n\r\nprintf("%d years, %d months, %d daysn", $years, $months, $days);\r\n</pre>', 24),
	(28, 'What is the difference between $name and $$name?', 'Syntax', '$name is variable where as $$name is reference variable like $name=sonia and $$name=singh so $sonia value is singh', 11),
	(29, 'What Is a Session?', 'Session and Cookies', 'A session is a logical object created by the PHP engine to allow you to preserve data across subsequent HTTP requests. Sessions are commonly used to store temporary data to allow multiple PHP pages to offer a complete functional transaction for the same visitor.', 7),
	(30, 'How can we register the variables into a session?', 'Session and Cookies', '<p>&lt;?php<br />\r\n	session_register($ur_session_var);<br />\r\n	?&gt;<br />\r\n	&nbsp;</p>\r\n<p>', 7),
	(31, 'How many ways we can pass the variable through the navigation between the pages?', 'Session and Cookies', '<ul>\r\n<li>Register the variable into the session</li>\r\n<li>Pass the variable as a cookie</li>\r\n<li>Pass the variable as part of the URL</li>\r\n</ul>', 7),
	(32, 'What is the functionality of the function strstr and stristr?', 'Strings', '<p><strong>strstr()</strong> returns part of a given string from the first occurrence of a given substring to the end of the string.<br />\r\nFor example:strstr(&quot;user@example.com&quot;,&quot;@&quot;) will return &quot;@example.com&quot;.<br />\r\n<strong>stristr()</strong> is idential to strstr() except that it is case insensitive.</p>', 7),
	(33, 'What is Constructors and Destructors?', 'OOP', '<p><strong>CONSTRUCTOR:</strong> PHP allows developers to declare constructor methods for classes. Classes which have a constructor method call this method on each newly-created object, so it is suitable for any initialization that the object may need before it is used.<br />\r\n<p><strong>DESTRUCTORS:</strong> PHP 5 introduces a destructor concept similar to that of other object-oriented languages, such as C++. The destructor method will be called as soon as all references to a particular object are removed or when the object is explicitly destroyed or in any order in shutdown sequence.</p>', 24),
	(34, 'What is use of header() function in php?', 'HTTP', '<p>The header() function sends a raw HTTP header to a client.We can use header()<br />\r\n	function for redirection of pages. It is important to notice that header() must<br />\r\n	be called before any actual output is seen.</p>', 23),
	(35, 'List out the predefined classes in PHP?', 'OOP', '<ul>\r\n<li>Directory</li>\r\n<li>stdClass</li>\r\n<li>__PHP_Incomplete_Class</li>\r\n<li>exception</li>\r\n<li>php_user_filter</li>\r\n</ul>', 24),
	(36, 'What type of inheritance that PHP supports?', 'OOP', 'In PHP an extended class is always dependent on a single base class,that is, multiple inheritance is not supported. Classes are extended using the keyword &#39;extends&#39;.', 24),
	(37, 'What is the difference between explode and split?', 'Strings', 'Split function splits string into array by regular expression. Explode splits a string into array by string.<br />\r\nFor Example:explode(&quot; and&quot;, &quot;India and Pakistan and Srilanka&quot;);<br />\r\n&nbsp;split(&quot; :&quot;, &quot;India : Pakistan : Srilanka&quot;);<br />\r\nBoth of these functions will return an array that contains India, Pakistan, and Srilanka.', 7),
	(38, 'What&rsquo;s the special meaning of __sleep and __wakeup?', 'OOP', '__sleep returns the array of all the variables than need to be saved, while __wakeup retrieves them.', 24),
	(39, 'What are the Formatting and Printing Strings available in PHP?', 'Strings', '<p><strong>printf()</strong>-&nbsp;&nbsp; &nbsp;Displays a formatted string<br />\r\n<strong>sprintf()</strong>-Saves a formatted string in a variable<br />\r\n<strong>fprintf()</strong>&nbsp;&nbsp; &nbsp;-Prints a formatted string to a file<br />\r\n<strong>number_format()</strong>-Formats numbers as strings</p>', 7),
	(40, 'What are the different tables types present in MySQL?', 'MySQL', '<p></em>Total 5 types of tables we can create<br>\r\n1. MyISAM<br>\r\n2. Heap<br>\r\n3. Merge<br>\r\n4. INNO DB<br>\r\n5. ISAM<br>\r\nMyISAM is the default storage engine as of MySQL 3.23 and as a result if we do not specify the table name explicitly it will be assigned to the default engine.</p>', 7),
	(41, 'How can I execute a PHP script using command line?', 'PHP Version', 'As of version 4.3.0, PHP supports a new SAPI type (Server Application Programming Interface) named CLI which means Command Line Interface. Just run the PHP CLI (Command Line Interface) program and provide the PHP script file name as the command line argument. For example, “php myScript.php”, assuming “php” is the command to invoke the CLI program.\r\nBe aware that if your PHP script was written for the Web CGI interface, it may not execute properly in command line environment.', 3),
	(42, 'How can we encrypt the username and password using PHP?', 'MySQL', '<p>The functions in this section perform encryption and decryption, and compression and uncompression:</p>\r\n<table border="0">\r\n<tbody>\r\n<tr>\r\n<td><strong>Encryption</strong></td>\r\n<td><strong>Decryption</strong></td>\r\n</tr>\r\n<tr>\r\n<td>AES_ENCRYPT()</td>\r\n<td>AES_DECRYPT()</td>\r\n</tr>\r\n<tr>\r\n<td>ENCODE()</td>\r\n<td>DECODE()</td>\r\n</tr>\r\n<tr>\r\n<td>DES_ENCRYPT()</td>\r\n<td>DES_DECRYPT()</td>\r\n</tr>\r\n<tr>\r\n<td>ENCRYPT()</td>\r\n<td>Not available</td>\r\n</tr>\r\n<tr>\r\n<td>MD5()</td>\r\n<td>Not available</td>\r\n</tr>\r\n<tr>\r\n<td>OLD_PASSWORD()</td>\r\n<td>Not available</td>\r\n</tr>\r\n<tr>\r\n<td>PASSWORD()</td>\r\n<td>Not available</td>\r\n</tr>\r\n<tr>\r\n<td>SHA() or SHA1()</td>\r\n<td>Not available</td>\r\n</tr>\r\n<tr>\r\n<td>Not available</td>\r\n<td>UNCOMPRESSED_LENGTH()</td>\r\n</tr>\r\n</tbody>\r\n</table>', 7),
	(43, 'What are the features and advantages of object-oriented programming?', 'OOP', 'One of the main advantages of OO programming is its ease of modification; objects can easily be modified and added to a system there by reducing maintenance costs. OO programming is also considered to be better at modeling the real world than is procedural programming. It allows for more complicated and flexible interactions. OO systems are also easier for non-technical personnel to understand and easier for them to participate in the maintenance and enhancement of a system because it appeals to natural human cognition patterns. For some systems, an OO approach can speed development time since many objects are standard across systems and can be reused. Components that manage dates, shipping, shopping carts, etc. can be purchased and easily modified for a specific system.', 24),
	(44, 'What are the differences between procedure-oriented languages and object-oriented languages?', 'OOP', 'Traditional programming has the following characteristics:Functions are written sequentially, so that a change in programming can affect any code that follows it. If a function is used multiple times in a system (i.e., a piece of code that manages the date), it is often simply cut and pasted into each program (i.e., a change log, order function, fulfillment system, etc). If a date change is needed (i.e., Y2K when the code needed to be changed to handle four numerical digits instead of two), all these pieces of code must be found, modified, and tested. Code (sequences of computer instructions) and data (information on which the instructions operates on) are kept separate. Multiple sets of code can access and modify one set of data. One set of code may rely on data in multiple places. Multiple sets of code and data are required to work together. Changes made to any of the code sets and data sets can cause problems through out the system.Object-Oriented programming takes a radically different approach:Code and data are merged into one indivisible item – an object (the term “component” has also been used to describe an object.) An object is an abstraction of a set of real-world things (for example, an object may be created around “date”) The object would contain all information and\r\nfunctionality for that thing (A date object it may contain labels like January, February, Tuesday, Wednesday.\r\nIt may contain functionality that manages leap years, determines if it is a business day or a holiday, etc., See Fig. 1). Ideally, information about a particular thing should reside in only one place in a system.The information within an object is encapsulated (or hidden) from the rest of the system. A system is composed of multiple objects (i.e., date function, reports, order processing, etc., See Fig 2). When one object needs information from another object, a request is sent asking for specific information. (for example, a report object may need to know what today’s date is and will send a request to the date object) These requests are called messages and each object has an interface that manages messages. OO programming languages include features such as “class”, “instance”, “inheritance”, and “polymorphism” that increase the power and\r\nflexibility of an object.', 24),
	(45, 'What are the differences between public, private, protected,static, transient, final and volatile?', 'OOP', '<p><strong>Public</strong>: Public declared items can be accessed everywhere.<br>\r\n<strong>Protected</strong>: Protected limits access to inherited and parent classes (and to the class that defines the item).<br>\r\n<strong>Private</strong>: Private limits visibility only to the class that defines the item.<br>\r\n<strong>Static</strong>: A static variable exists only in a local function scope, but it does not lose its value when program execution leaves this scope.<br>\r\n<strong>Final</strong>: Final keyword prevents child classes from overriding a method by prefixing the definition with final. If the class itself is being defined final then it cannot be extended.<br>\r\n<strong>Transient</strong>: A transient variable is a variable that may not be serialized.<br>\r\n<strong>Volatile</strong>: a variable that might be concurrently modified by multiple threads should be declared volatile. Variables declared to be volatile will not be optimized by the compiler because their value can change at any time.</p>', 24),
	(46, 'What are the different types of errors in PHP?', 'Errors', '<p>Three are three types of errors:</p>\r\n<ul>\r\n	<li>Notices: These are trivial, non-critical errors that PHP encounters while executing a script - for example, accessing a variable that has not yet been defined. By default, such errors are not displayed to the user at all – although, as you will see, you can change this default behavior.</li>\r\n	<li>Warnings: These are more serious errors – for example, attempting to include() a file which does not exist. By default, these errors are displayed to the user, but they do not result in script termination.</li>\r\n	<li>Fatal errors: These are critical errors – for example, instantiating an object of a non-existent class, or calling a non-existent function. These errors cause the immediate termination of the script, and PHP’s default behavior is to display them to the user when they take place.</li>\r\n</ul>', 7),
	(47, 'What are the difference between abstract class and interface?', 'OOP', '<p><em>Abstract class</em>: abstract classes are the class where one or moremethods are abstract but not necessarily all method has to be abstract.</p>', 24),
	(48, 'What are the advantages of stored procedures, triggers, indexes?', 'MySQL', '<p><strong>Answer</strong><em> : </em>A stored procedure is a set of SQL commands that can be compiled and stored in the server. Once this has been done, clients don’t need tokeep re-issuing the entire query but can refer to the stored <span class="skimlinks-unlinked">procedure.This</span> provides better overall performance because the query has to beparsed only once, and less information needs to be sent between theserver and the client. You can also raise the conceptual level by havinglibraries of functions in the server. However, stored procedures ofcourse do increase the load on the database server <a id="KonaLink5" class="kLink" href="http://www.shashionline.in/2008/08/02/php-interview-question/#" target="_top" sl-processed="1"></a>system, as more of the work is done on the server side and less on the client (application)side.Triggers will also be implemented. A trigger is effectively a type of stored procedure, one that is invoked when a particular event <span class="skimlinks-unlinked">occurs.For</span> example, you can install a stored procedure that is triggered each time a record is deleted from a transaction table and that stored procedure automatically deletes the corresponding customer from a customer table when all his transactions are deleted.Indexes are used to find rows with specific column values quickly.Without an index, MySQL must begin with the first row and then read through the entire table to find the relevant rows. The larger the table, the more this costs. If the table has an index for the columns in question, MySQL can quickly determine the position to seek to in the middle of the data file without having to look at all the data. If a table has 1,000 rows, this is at least 100 times faster than reading sequentially. If you need to access most of the rows, it is faster to read sequentially, because this minimizes disk seeks.</p>', 7),
	(49, 'What is the maximum length of a table name, database name and field name in MySQL?', 'MySQL', '<p>The following table describes the maximum length for each type of identifier.</p>\r\n<table border="0">\r\n<tbody>\r\n<tr>\r\n<td>Identifier</td>\r\n<td>Maximum Length(bytes)</td>\r\n</tr>\r\n<tr>\r\n<td>Database</td>\r\n<td>64</td>\r\n</tr>\r\n<tr>\r\n<td>Table</td>\r\n<td>64</td>\r\n</tr>\r\n<tr>\r\n<td>Column</td>\r\n<td>64</td>\r\n</tr>\r\n<tr>\r\n<td>Index</td>\r\n<td>64</td>\r\n</tr>\r\n<tr>\r\n<td>Alias</td>\r\n<td>255</td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n<p>There are some restrictions on the characters that may appear in identifiers.</p>', 7),
	(50, 'What is class?', 'OOP', 'Class is a collection of variables and method.', 24),
	(51, 'What is data encapsulation and how to achieve it PHP?', 'OOP', 'Data encapsulation is hiding the member variables and method from the access of others.In PHP data encapsulation is implementated with concept called Class. Class is the collection of variable and method whoes access to other classes is defined in the class  itself.', 24),
	(52, 'What is the difference between errors and exceptions?', 'Errors', 'An error is a fatal to the programs’s ability to do its job. Where as an exception is a stituation which is uncommon but recoverable.', 7),
	(53, 'What is HTTP?', 'HTTP', 'The Hypertext Transfer Protocol (HTTP) is an application protocol for distributed, collaborative, hypermedia information systems.[1] HTTP is the foundation of data communication for the World Wide Web.', 23);
/*!40000 ALTER TABLE `interview` ENABLE KEYS */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
